### ISSUE TITLE
`=` missing in lexactivator_native.py

### ISSUE THREAD

**Issue by piotlinski** [cryptlex/lexactivator-python#10]
It seems latest version has a bug in lexactivator_native.py (`=` is missing):

https://github.com/cryptlex/lexactivator-python/blob/1c435b2a66daf08a9589364d690de289ade3857a/cryptlex/lexactivator/lexactivator_native.py#L185

**Comment by adnan-kamili** [comment]
fixed, thanks for reporting. Please update to v3.16.1
